Change code block handlebars
ember-learn/ember-blog pull request #1010
Opened 2021-07-30 20:46 UTC by amyrlam

## What it does

- [ ] Needs documentation, will add but want to see GitHub actions fire

## Related Issue(s)

## Sources

2021-07-31 01:41 UTC, NullVoxPopuli commented
You can use hbs and better highlighting with this: (I did the name fix earlier today): https://github.com/NullVoxPopuli/website/pull/45/files#diff-322f0482bd28fc40f84fcb0aaf208fef7fb63082d462cf02d11f46e59c531c24R6

2021-07-31 03:23 UTC, amyrlam commented
@NullVoxPopuli thank you!

- This works but I'm not sure if ember-prism should be installed here or somewhere up the chain in empress. But didn't see anything for "prism" in https://github.com/empress/empress-blog-casper-template. I could be missing something, do you know, @mansona or others?
- I can separate out the `npx browserslist@latest --update-db` change, in debugging was doing a few things.

2021-07-31 04:44 UTC, NullVoxPopuli commented
I mean, I think this should be a default in ember-prism, but I don't remember why it's not 🤔

This is the PR that introduced it: https://github.com/shipshapecode/ember-prism/pull/279

But I don't see a discussion about it. 🤔 

@rwwagner90 thoughts on making prism-glimmer default? I'm not sure how it would work - not supes familiar with how prism is bundled / is running

2021-08-02 15:28 UTC, ijlee2 requested changes
@amyrlam I think you added the `ember-prism` package because, without it, running `start()` will result in the error,

```
Error: Could not find module `ember-prism` imported from `ember-blog/app`
```

However, `ember-prism` already gets pulled in through `empress-blog-ember-template`. I'm unsure what having a separate package will mean for us in the long run.

For simplicity, can we:

- Revert the changes to `app/app.js`, `ember-cli-build.js`, `package.json`, and `package-lock.json`
- Use `handlebars` instead of `html` in the file `content/the-ember-times-issue-184.md`

2021-08-02 15:30 UTC, ijlee2 commented on CONTRIBUTING.md
> +{{something-cool}}
I think the following code example may illustrate when to use `handlebars` better?

```suggestion
{{!-- app/templates/application.hbs --}}

<h1>Hello world!</h1>

{{outlet}}
```

2021-08-02 15:39 UTC, amyrlam commented
@ijlee2 Makes sense... was thinking to update upstream. It looks like upstream is using `ember-showdown-prism` though, which builds on `ember-prism` https://github.com/ember-learn/empress-blog-ember-template/blob/master/package.json#L43 ... let me do some investigation there. Thanks for the feedback!

2021-08-02 19:09 UTC, NullVoxPopuli commented
Fwiw, embroider requires packages that are imported in app code to be declared in package.json

2021-08-12 15:13 UTC, jenweber commented on content/the-ember-times-issue-184.md
> +```hbs
This should be `handlebars` instead. Maybe it will work after that change?

In the learning team discussion - if there is an issue with prism, bugfixes would need to go upstream in https://github.com/empress/ember-showdown-prism

2021-08-12 15:19 UTC, mansona requested changes

2021-08-12 15:19 UTC, mansona commented on app/app.js
> +import { setup } from 'ember-prism';
just to follow up to what @jenweber said, we should not be doing anything ember-prism directly in ember-blog. This is all handled by the template and the addon that Jen already mentioned 👍

2021-08-12 15:20 UTC, NullVoxPopuli commented on content/the-ember-times-issue-184.md
> +```hbs
if high-glimmer is enabled, `hbs` works fine

2021-08-15 18:17 UTC, amyrlam commented
@jenweber @mansona i'm not sure exactly what you are suggesting, can u clarify what u mean?

suggestion: why don't i go back to @ijlee2's suggestion https://github.com/ember-learn/ember-blog/pull/1010#pullrequestreview-720333259 and file an issue on ember-showdown-prism, which doesn't seem to be bringing in the latest changes to ember-prism yet that @NullVoxPopuli did. 

i'm going to work on the times first and get back to this task next. sorry for the delay have been sick.

2021-08-17 05:53 UTC, amyrlam commented
i've made this issue upstream, to hopefully look at later: https://github.com/empress/ember-showdown-prism/issues/17

i tagged the four of you on https://github.com/ember-learn/ember-blog/pull/1019 and am closing this PR in favor of that one!

2021-08-17 05:53 UTC, closed without merging