Add writeup on ember-element-query
ember-learn/ember-blog pull request #1037
Opened 2021-09-21 04:35 UTC by amyrlam

## Ember Times review template

- [x] Add your name to top and bottom
- [x] Put emoji in writeup title
- [x] Add a short blurb (could be the title) to the beginning
- [x] Link to external article/repo/etc in paragraph/body text, not just the writeup title (link in writeup title is optional now)
- [x] Add the contributor in the post in format "FirstName LastName (@githubUserName)" linked to their GitHub account
- [ ] Check that all links work

2021-09-21 04:44 UTC, amyrlam commented
@lolmaus hey, if you want to check out this quick writeup for friday's ember times and have any feedback, let me know! no pressure though

2021-09-21 05:01 UTC, lolmaus commented
@amyrlam Yes, gladly.

I might have something to add.

2021-09-21 10:55 UTC, ijlee2 approved these changes
🎉

2021-09-21 17:32 UTC, amyrlam commented
@lolmaus cool thanks, just let me know! feel free to use a github suggestion or make a commit if easier

BTW it sounds cool, i want to try it out myself, hopefully 🔜

2021-09-23 08:29 UTC, lolmaus requested changes
I hope it's not too late! 🙏

2021-09-23 08:29 UTC, lolmaus commented on content/the-ember-times-issue-189.md
> +Check out the detailed [README](https://github.com/lolmaus/ember-element-query/) and give the addon a spin! ember-element-query builds on the work started by [ember-fill-up](https://github.com/chadia
Not sure if this level of detail is appropriate, but I would like to share some historical context and give due credit.

This suggestion also splits two "Check out..." sentences further apart.

```suggestion
Historically, `ember-element-query` was the first Ember addon to offer element queries out of the box, but back then it used an inefficient implementation and was written in the now-outdated Classic Ember paradigm. It served as one of inspirations for [Chad Carbert's (@chadian)](https://github.com/chadian) [ember-fill-up](https://github.com/chadian/ember-fill-up). Announced on EmberFest 2019 as a proof-of-concept, `ember-fill-up` saw no updates and was discontinued.

The first element query addon to be released with feature completeness, full test coverage and lasting support was [Isaac Lee's (@ijlee2)](https://github.com/ijlee2/) `ember-container-query`, featured in [The Ember Times #153](https://blog.emberjs.com/the-ember-times-issue-153/). The re-release of `ember-element-query` followed suit with a subjectively more convenient, opinionated API, backed by modern, efficient `ResizeObserver` under the hood. [@ijlee2](https://github.com/ijlee2/) provided kind support, criticism and generously shared the demo app with [@lolmaus](https://github.com/lolmaus)'s `ember-element-query`.

Check out the detailed [README](https://github.com/lolmaus/ember-element-query/) and give the addon a spin! 
```

2021-09-23 08:30 UTC, lolmaus commented on content/the-ember-times-issue-189.md
> +Check out the detailed [README](https://github.com/lolmaus/ember-element-query/) and give the addon a spin! ember-element-query builds on the work started by [ember-fill-up](https://github.com/chadia
On the Conversation tab, the suggested edit has no line breaks. Line breaks are available at the Files changed tab.

2021-09-23 15:53 UTC, amyrlam commented on content/the-ember-times-issue-189.md
> +Check out the detailed [README](https://github.com/lolmaus/ember-element-query/) and give the addon a spin! ember-element-query builds on the work started by [ember-fill-up](https://github.com/chadia
@lolmaus this is awesome, thank you!

2021-09-23 16:21 UTC, amyrlam commented
merging in, looks great! we publish every 2 fridays in the pacific PM. thanks again @lolmaus and @ijlee2!

2021-09-23 16:21 UTC, merged