Embroider again again
ember-learn/ember-blog pull request #1169
Opened 2022-06-27 16:43 UTC by NullVoxPopuli

## Ember Times review template

- [ ] Add your name to top and bottom
- [ ] Put emoji in writeup title
- [ ] Add a short blurb (could be the title) to the beginning
- [ ] Link to external article/repo/etc in paragraph/body text, not just the writeup title (link in writeup title is optional now)
- [ ] Add the contributor in the post in format "FirstName LastName (@githubUserName)" linked to their GitHub account
- [ ] Check that all links work

## What it does

## Related Issue(s)

## Sources

2022-06-27 21:12 UTC, NullVoxPopuli commented
deploy is broken? :shrug:

2022-06-29 23:39 UTC, jenweber commented
This is a guess - maybe try adding a file for yourself in the `author` directory, for example see `author/jen-weber.md`. I see an error in CI about the `2022` tag but I wonder if that's a side effect. Nothing else in this PR jumps out.

2022-06-30 00:21 UTC, jaredgalanis commented
> deploy is broken? 🤷

@NullVoxPopuli, there was some wonkiness in the original branch for the 201 Issue (it was based on a really old state of main), that you based your branch on. I'm pretty sure the deploy issues were related. Because of the wonkiness, I created a new branch and PR. Can you please try to either rebase your branch on `blog/embertimes-201-v2` or cut a new branch that's based on that and cherry-pick your commit over (that may be the easiest route, not sure).

Apologies for the further hassle! We'll get this reviewed and in the next issue. 😊

2022-06-30 00:29 UTC, jaredgalanis commented
> > deploy is broken? 🤷
> 
> @NullVoxPopuli, there was some wonkiness in the original branch for the 201 Issue (it was based on a really old state of main), that you based your branch on. I'm pretty sure the deploy issues were related. Because of the wonkiness, I created a new branch and PR. Can you please try to either rebase your branch on `blog/embertimes-201-v2` or cut a new branch that's based on that and cherry-pick your commit over (that may be the easiest route, not sure).
> 
> Apologies for the further hassle! We'll get this reviewed and in the next issue. 😊

Update: I actually just reset the state of the original `blog/embertimes-201` branch and force pushed it. You have conflicts now, but a rebase should be pretty simple.

2022-06-30 00:39 UTC, jaredgalanis requested changes
Looks good to me. One small thing.

2022-06-30 00:39 UTC, jaredgalanis commented on content/the-ember-times-issue-201.md
> +Note that while some addons may break your build, this may be for the greater good. For example, instead of relying on ember-specific solutions to certain build-time behaviors, you may now follow hea
It looks like this paragraph is inheriting the block-quote from above, so it reads as if it's part of the quote from the `README.md`. I think maybe inserting a line between will fix it.

2022-07-10 23:39 UTC, merged

2022-07-11 15:29 UTC, angelayanpan commented
just saw this. Thanks for the PR! and it's already published.  so I don't know if we can still fix anything? it should be `released mid January 2022`  not 2021

2022-07-11 16:08 UTC, jaredgalanis commented
Thanks @angelayanpan. We can fix it on the blog site, but not in the email that was sent.

2022-07-11 16:33 UTC, angelayanpan commented
ok, that works @jaredgalanis  thank you! are you able to update the blog? or that requires a separate PR?

2022-07-11 16:38 UTC, jaredgalanis commented
> ok, that works @jaredgalanis  thank you! are you able to update the blog? or that requires a separate PR? 

For sure, thank you for finding it!

I'll fix it in a little bit here. 

Let us know if you are interested in writing for the Times ever. We always can use help. 😊

2022-07-11 17:34 UTC, jaredgalanis commented
> ok, that works @jaredgalanis thank you! are you able to update the blog? or that requires a separate PR?

@angelayanpan it's fixed on the blog site now.