add blurb about jsQR
ember-learn/ember-blog pull request #561
Opened 2020-03-09 16:28 UTC by NullVoxPopuli

does the GH PR template need to be updated for ember-times submissions? idk how'd that work, but nothing made sense, so I deleted it all :-/

2020-03-09 22:02 UTC, MinThaMie requested changes
You forgot to add your part to the intro :(

2020-03-09 22:04 UTC, NullVoxPopuli commented
What intro? :/

2020-03-10 09:25 UTC, MinThaMie approved these changes

2020-03-10 09:25 UTC, MinThaMie commented on source/2020-03-13-the-ember-times-issue-139.md
> +QR scanning without bundle size growing!
```suggestion
QR scanning without bundle size growing 📷!
```

2020-03-12 03:36 UTC, ijlee2 commented
I'll merge this so that I and others can branch off from the latest, thanks.

2020-03-12 03:36 UTC, merged